export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900">
            <nav className="fixed top-0 left-0 right-0 z-50 backdrop-blur-md bg-slate-900/70 border-b border-slate-700/50">
                <div className="max-w-6xl mx-auto px-6 py-4 flex items-center gap-2">
                    <a href="/" className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-sky-400 to-blue-600 flex items-center justify-center">
                            <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                            </svg>
                        </div>
                        <span className="text-xl font-bold text-white">PFactor</span>
                    </a>
                </div>
            </nav>

            <div className="max-w-3xl mx-auto px-6 pt-28 pb-20">
                <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
                <p className="text-slate-400 mb-10">Last updated: April 8, 2026</p>

                <div className="space-y-8 text-slate-300 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By downloading or using PFactor, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the app.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
                        <p>PFactor is an AI-powered oral exam practice application for FAA pilot certification. The app provides simulated oral exam questions, AI-generated feedback, and progress tracking. PFactor is a study tool only and is not affiliated with, endorsed by, or approved by the FAA or any official aviation authority.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">3. Not a Substitute for Official Training</h2>
                        <p className="font-medium text-yellow-400">PFactor is designed to supplement — not replace — official FAA training, flight instruction, or approved ground school. Content generated by AI may contain errors or omissions. Always verify information against current FAA regulations, ACS standards, and guidance from a certified flight instructor.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. Subscriptions and Billing</h2>
                        <p>PFactor offers auto-renewing subscription plans billed through the Apple App Store:</p>
                        <ul className="list-disc list-inside mt-2 space-y-1 text-slate-400">
                            <li>Monthly subscription at $19.99/month</li>
                            <li>Annual subscription at $149.99/year</li>
                        </ul>
                        <p className="mt-3">Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period. You can manage and cancel subscriptions in your Apple ID account settings. No refunds are provided for partial subscription periods.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. Free Tier</h2>
                        <p>Free accounts are limited to 3 quick practice sessions per week. All other exam modes require an active Premium subscription.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">6. Account</h2>
                        <p>You are responsible for maintaining the security of your account. You may not share your account credentials. We reserve the right to terminate accounts that violate these terms.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
                        <p>All content, design, and code within PFactor is the property of the developer. FAA ACS standards and regulatory content are public domain. You may not reproduce, distribute, or create derivative works from PFactor without permission.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">8. Disclaimer of Warranties</h2>
                        <p>PFactor is provided &quot;as is&quot; without warranties of any kind. We do not warrant that the app will be error-free, uninterrupted, or that AI-generated content will be accurate or complete.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
                        <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, or consequential damages arising from your use of PFactor, including any reliance on AI-generated content during actual flight training or examination.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">10. Changes to Terms</h2>
                        <p>We reserve the right to modify these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">11. Contact</h2>
                        <p>Questions about these Terms of Service can be directed to:</p>
                        <p className="mt-2 text-sky-400">support@pfactor.app</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
